name: Update Lists

on:
  push:
    paths:
      - 'list_generator*'
      - '.github/workflows/update_lists.yml'
  workflow_dispatch:

jobs:
  update-lists:
    runs-on: ubuntu-latest
    env:
      python: '3.x'
      dnspython: '2.1.0'

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python }}

      - name: Check Python3 Version
        run: python3 --version
    
      - name: Run list_generator.sh
        run: |
          echo 'previos state ...'
          wc -l ipv?_list.txt
          chmod +x list_generator.sh
          ./list_generator.sh
          echo 'new state ...'
          wc -l ipv?_list.txt

      - name: Installing dnspython-${{ env.dnspython }} and Generating Lists
        run: |
          pip3 install --upgrade pip
          pip3 install -I dnspython==${{ env.dnspython }}
          python3 ./list_generator.py

      - name: Update IP count in README.md
        run: |
          TOTAL_IPS=$(wc -l ipv?_list.txt | grep -oP '\d+(?=\s+total)')
          sed -i -E "s|\*\*[0-9]+\*\*|**$TOTAL_IPS**|" README.md

      - name: Commit changes
        run: |
          git config --local user.email '46617994+touhidurrr@users.noreply.github.com'
          git config --local user.name 'touhidurrr'
          git add ipv?_list.txt README.md
          git commit -m 'Updated Lists [Automated]'
          git pull
          git push

      - name: Check diff
        run: git diff HEAD..HEAD~1
